# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/App.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 491, 381))
        self.groupBox.setObjectName("groupBox")
        self.label_videoFrame = QtWidgets.QLabel(self.groupBox)
        self.label_videoFrame.setGeometry(QtCore.QRect(10, 20, 471, 351))
        self.label_videoFrame.setObjectName("label_videoFrame")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(510, 10, 501, 541))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableView_Data = QtWidgets.QTableView(self.groupBox_2)
        self.tableView_Data.setGeometry(QtCore.QRect(10, 20, 481, 511))
        self.tableView_Data.setObjectName("tableView_Data")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 400, 491, 151))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        self.menuFime = QtWidgets.QMenu(self.menubar)
        self.menuFime.setObjectName("menuFime")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionConfig_Customer = QtWidgets.QAction(MainWindow)
        self.actionConfig_Customer.setObjectName("actionConfig_Customer")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionConfig_Item = QtWidgets.QAction(MainWindow)
        self.actionConfig_Item.setObjectName("actionConfig_Item")
        self.actionConfig_Invoice = QtWidgets.QAction(MainWindow)
        self.actionConfig_Invoice.setObjectName("actionConfig_Invoice")
        self.actionConfig_Employee = QtWidgets.QAction(MainWindow)
        self.actionConfig_Employee.setObjectName("actionConfig_Employee")
        self.menuFime.addAction(self.actionQuit)
        self.menuSetting.addAction(self.actionConfig_Customer)
        self.menuSetting.addAction(self.actionConfig_Employee)
        self.menuSetting.addAction(self.actionConfig_Item)
        self.menuSetting.addAction(self.actionConfig_Invoice)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFime.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Camera Detection"))
        self.groupBox.setTitle(_translate("MainWindow", "Camera"))
        self.label_videoFrame.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_2.setTitle(_translate("MainWindow", "History"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "VKU"))
        self.menuFime.setTitle(_translate("MainWindow", "File"))
        self.menuSetting.setTitle(_translate("MainWindow", "Settings"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionConfig_Customer.setText(_translate("MainWindow", "Config Customer"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionConfig_Item.setText(_translate("MainWindow", "Config Item"))
        self.actionConfig_Invoice.setText(_translate("MainWindow", "Config Invoice"))
        self.actionConfig_Employee.setText(_translate("MainWindow", "Config Employee"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
