# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/ConfigInvoice.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_ConfigModel(object):
    def setupUi(self, Dialog_ConfigModel):
        Dialog_ConfigModel.setObjectName("Dialog_ConfigModel")
        Dialog_ConfigModel.resize(800, 600)
        self.pushButton_Close = QtWidgets.QPushButton(Dialog_ConfigModel)
        self.pushButton_Close.setGeometry(QtCore.QRect(710, 560, 75, 23))
        self.pushButton_Close.setObjectName("pushButton_Close")
        self.groupBox = QtWidgets.QGroupBox(Dialog_ConfigModel)
        self.groupBox.setGeometry(QtCore.QRect(20, 270, 211, 271))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_CreateInvoice = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_CreateInvoice.setGeometry(QtCore.QRect(60, 70, 91, 31))
        self.pushButton_CreateInvoice.setObjectName("pushButton_CreateInvoice")
        self.comboBox_Customer = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Customer.setGeometry(QtCore.QRect(8, 40, 191, 22))
        self.comboBox_Customer.setObjectName("comboBox_Customer")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_5.setObjectName("label_5")
        self.tableView_InvoiceHeader = QtWidgets.QTableView(Dialog_ConfigModel)
        self.tableView_InvoiceHeader.setGeometry(QtCore.QRect(20, 10, 761, 251))
        self.tableView_InvoiceHeader.setObjectName("tableView_InvoiceHeader")
        self.pushButton_Clear = QtWidgets.QPushButton(Dialog_ConfigModel)
        self.pushButton_Clear.setGeometry(QtCore.QRect(610, 560, 75, 23))
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog_ConfigModel)
        self.groupBox_2.setGeometry(QtCore.QRect(240, 270, 241, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_Quantity = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Quantity.setEnabled(False)
        self.lineEdit_Quantity.setGeometry(QtCore.QRect(10, 90, 221, 20))
        self.lineEdit_Quantity.setObjectName("lineEdit_Quantity")
        self.comboBox_Item = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_Item.setEnabled(False)
        self.comboBox_Item.setGeometry(QtCore.QRect(10, 40, 221, 22))
        self.comboBox_Item.setObjectName("comboBox_Item")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 81, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_Money = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Money.setEnabled(False)
        self.lineEdit_Money.setGeometry(QtCore.QRect(10, 140, 221, 20))
        self.lineEdit_Money.setReadOnly(True)
        self.lineEdit_Money.setObjectName("lineEdit_Money")
        self.pushButton_AddItem = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_AddItem.setEnabled(False)
        self.pushButton_AddItem.setGeometry(QtCore.QRect(70, 180, 91, 31))
        self.pushButton_AddItem.setObjectName("pushButton_AddItem")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog_ConfigModel)
        self.groupBox_3.setGeometry(QtCore.QRect(490, 270, 291, 271))
        self.groupBox_3.setObjectName("groupBox_3")
        self.tableView_InvoiceDetail = QtWidgets.QTableView(self.groupBox_3)
        self.tableView_InvoiceDetail.setGeometry(QtCore.QRect(10, 50, 271, 171))
        self.tableView_InvoiceDetail.setObjectName("tableView_InvoiceDetail")
        self.pushButton_SaveInvoice = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_SaveInvoice.setEnabled(False)
        self.pushButton_SaveInvoice.setGeometry(QtCore.QRect(110, 230, 91, 31))
        self.pushButton_SaveInvoice.setObjectName("pushButton_SaveInvoice")
        self.lineEdit_InvoiceCode = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_InvoiceCode.setGeometry(QtCore.QRect(80, 20, 201, 20))
        self.lineEdit_InvoiceCode.setReadOnly(True)
        self.lineEdit_InvoiceCode.setObjectName("lineEdit_InvoiceCode")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog_ConfigModel)
        self.pushButton_Close.clicked.connect(Dialog_ConfigModel.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_ConfigModel)
        Dialog_ConfigModel.setTabOrder(self.tableView_InvoiceHeader, self.pushButton_Clear)
        Dialog_ConfigModel.setTabOrder(self.pushButton_Clear, self.pushButton_Close)

    def retranslateUi(self, Dialog_ConfigModel):
        _translate = QtCore.QCoreApplication.translate
        Dialog_ConfigModel.setWindowTitle(_translate("Dialog_ConfigModel", "Config Invoice"))
        self.pushButton_Close.setText(_translate("Dialog_ConfigModel", "Close"))
        self.groupBox.setTitle(_translate("Dialog_ConfigModel", "Step 1: Choose one customer of invoice"))
        self.pushButton_CreateInvoice.setText(_translate("Dialog_ConfigModel", "1.Create Invoice"))
        self.label_5.setText(_translate("Dialog_ConfigModel", "Customer (*)"))
        self.pushButton_Clear.setText(_translate("Dialog_ConfigModel", "Clear"))
        self.groupBox_2.setTitle(_translate("Dialog_ConfigModel", "Step 2: Add items to invoice"))
        self.label_7.setText(_translate("Dialog_ConfigModel", "Quantity (*)"))
        self.label_4.setText(_translate("Dialog_ConfigModel", "Item (*)"))
        self.label_8.setText(_translate("Dialog_ConfigModel", "Money"))
        self.pushButton_AddItem.setText(_translate("Dialog_ConfigModel", "2.Add Item"))
        self.groupBox_3.setTitle(_translate("Dialog_ConfigModel", "Step 3: Preview and submit invoice"))
        self.pushButton_SaveInvoice.setText(_translate("Dialog_ConfigModel", "3. Save Invoice"))
        self.label_2.setText(_translate("Dialog_ConfigModel", "Invoice Code"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_ConfigModel = QtWidgets.QDialog()
    ui = Ui_Dialog_ConfigModel()
    ui.setupUi(Dialog_ConfigModel)
    Dialog_ConfigModel.show()
    sys.exit(app.exec_())
