# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/ConfigCustomer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_ConfigModel(object):
    def setupUi(self, Dialog_ConfigModel):
        Dialog_ConfigModel.setObjectName("Dialog_ConfigModel")
        Dialog_ConfigModel.resize(800, 600)
        self.pushButton_Close = QtWidgets.QPushButton(Dialog_ConfigModel)
        self.pushButton_Close.setGeometry(QtCore.QRect(710, 560, 75, 23))
        self.pushButton_Close.setObjectName("pushButton_Close")
        self.groupBox = QtWidgets.QGroupBox(Dialog_ConfigModel)
        self.groupBox.setGeometry(QtCore.QRect(20, 250, 341, 301))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(140, 20, 131, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_CustomerName = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_CustomerName.setGeometry(QtCore.QRect(140, 40, 191, 20))
        self.lineEdit_CustomerName.setObjectName("lineEdit_CustomerName")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 145, 131, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit_CMTND = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_CMTND.setGeometry(QtCore.QRect(10, 40, 121, 20))
        self.lineEdit_CMTND.setReadOnly(False)
        self.lineEdit_CMTND.setObjectName("lineEdit_CMTND")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_Phone = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Phone.setGeometry(QtCore.QRect(10, 90, 121, 20))
        self.lineEdit_Phone.setObjectName("lineEdit_Phone")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(140, 70, 81, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_Address = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Address.setGeometry(QtCore.QRect(140, 90, 191, 20))
        self.lineEdit_Address.setObjectName("lineEdit_Address")
        self.graphicsView_Image = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView_Image.setGeometry(QtCore.QRect(140, 150, 191, 141))
        self.graphicsView_Image.setObjectName("graphicsView_Image")
        self.checkBox_Retraining = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Retraining.setGeometry(QtCore.QRect(10, 120, 211, 21))
        self.checkBox_Retraining.setObjectName("checkBox_Retraining")
        self.pushButton_Insert = QtWidgets.QPushButton(Dialog_ConfigModel)
        self.pushButton_Insert.setGeometry(QtCore.QRect(290, 560, 75, 23))
        self.pushButton_Insert.setObjectName("pushButton_Insert")
        self.pushButton_Delete = QtWidgets.QPushButton(Dialog_ConfigModel)
        self.pushButton_Delete.setGeometry(QtCore.QRect(490, 560, 75, 23))
        self.pushButton_Delete.setObjectName("pushButton_Delete")
        self.tableView_customerList = QtWidgets.QTableView(Dialog_ConfigModel)
        self.tableView_customerList.setGeometry(QtCore.QRect(20, 10, 761, 231))
        self.tableView_customerList.setObjectName("tableView_customerList")
        self.pushButton_Update = QtWidgets.QPushButton(Dialog_ConfigModel)
        self.pushButton_Update.setGeometry(QtCore.QRect(390, 560, 75, 23))
        self.pushButton_Update.setObjectName("pushButton_Update")
        self.pushButton_Clear = QtWidgets.QPushButton(Dialog_ConfigModel)
        self.pushButton_Clear.setGeometry(QtCore.QRect(190, 560, 75, 23))
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog_ConfigModel)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 250, 411, 301))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_videoFrame = QtWidgets.QLabel(self.groupBox_2)
        self.label_videoFrame.setGeometry(QtCore.QRect(10, 20, 391, 271))
        self.label_videoFrame.setObjectName("label_videoFrame")

        self.retranslateUi(Dialog_ConfigModel)
        self.pushButton_Close.clicked.connect(Dialog_ConfigModel.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_ConfigModel)
        Dialog_ConfigModel.setTabOrder(self.tableView_customerList, self.lineEdit_CMTND)
        Dialog_ConfigModel.setTabOrder(self.lineEdit_CMTND, self.lineEdit_CustomerName)
        Dialog_ConfigModel.setTabOrder(self.lineEdit_CustomerName, self.lineEdit_Phone)
        Dialog_ConfigModel.setTabOrder(self.lineEdit_Phone, self.lineEdit_Address)
        Dialog_ConfigModel.setTabOrder(self.lineEdit_Address, self.pushButton_Clear)
        Dialog_ConfigModel.setTabOrder(self.pushButton_Clear, self.pushButton_Insert)
        Dialog_ConfigModel.setTabOrder(self.pushButton_Insert, self.pushButton_Update)
        Dialog_ConfigModel.setTabOrder(self.pushButton_Update, self.pushButton_Delete)
        Dialog_ConfigModel.setTabOrder(self.pushButton_Delete, self.pushButton_Close)

    def retranslateUi(self, Dialog_ConfigModel):
        _translate = QtCore.QCoreApplication.translate
        Dialog_ConfigModel.setWindowTitle(_translate("Dialog_ConfigModel", "Config Customer"))
        self.pushButton_Close.setText(_translate("Dialog_ConfigModel", "Close"))
        self.groupBox.setTitle(_translate("Dialog_ConfigModel", "Information"))
        self.label_2.setText(_translate("Dialog_ConfigModel", "Customer Name (*)"))
        self.label_4.setText(_translate("Dialog_ConfigModel", "Mobile Phone"))
        self.label_3.setText(_translate("Dialog_ConfigModel", "(*) : Input is requirement"))
        self.label_5.setText(_translate("Dialog_ConfigModel", "CMTND (*)"))
        self.label_7.setText(_translate("Dialog_ConfigModel", "Address"))
        self.checkBox_Retraining.setText(_translate("Dialog_ConfigModel", "Retraining Image (Only when update)"))
        self.pushButton_Insert.setText(_translate("Dialog_ConfigModel", "Add New"))
        self.pushButton_Delete.setText(_translate("Dialog_ConfigModel", "Delete"))
        self.pushButton_Update.setText(_translate("Dialog_ConfigModel", "Update"))
        self.pushButton_Clear.setText(_translate("Dialog_ConfigModel", "Clear"))
        self.groupBox_2.setTitle(_translate("Dialog_ConfigModel", "Camera"))
        self.label_videoFrame.setText(_translate("Dialog_ConfigModel", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_ConfigModel = QtWidgets.QDialog()
    ui = Ui_Dialog_ConfigModel()
    ui.setupUi(Dialog_ConfigModel)
    Dialog_ConfigModel.show()
    sys.exit(app.exec_())
