# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/ConfigEmployee.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_ConfigModel(object):
    def setupUi(self, Dialog_ConfigModel):
        Dialog_ConfigModel.setObjectName("Dialog_ConfigModel")
        Dialog_ConfigModel.resize(800, 600)
        self.pushButton_Close = QtWidgets.QPushButton(Dialog_ConfigModel)
        self.pushButton_Close.setGeometry(QtCore.QRect(710, 560, 75, 23))
        self.pushButton_Close.setObjectName("pushButton_Close")
        self.groupBox = QtWidgets.QGroupBox(Dialog_ConfigModel)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 231, 201))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 131, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_EmployeeName = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_EmployeeName.setGeometry(QtCore.QRect(10, 90, 211, 20))
        self.lineEdit_EmployeeName.setObjectName("lineEdit_EmployeeName")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 131, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_EmployeeCode = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_EmployeeCode.setGeometry(QtCore.QRect(10, 40, 211, 20))
        self.lineEdit_EmployeeCode.setReadOnly(False)
        self.lineEdit_EmployeeCode.setObjectName("lineEdit_EmployeeCode")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_Email = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Email.setGeometry(QtCore.QRect(10, 140, 211, 20))
        self.lineEdit_Email.setObjectName("lineEdit_Email")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 131, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_Insert = QtWidgets.QPushButton(Dialog_ConfigModel)
        self.pushButton_Insert.setGeometry(QtCore.QRect(150, 240, 75, 23))
        self.pushButton_Insert.setObjectName("pushButton_Insert")
        self.pushButton_Delete = QtWidgets.QPushButton(Dialog_ConfigModel)
        self.pushButton_Delete.setGeometry(QtCore.QRect(150, 280, 75, 23))
        self.pushButton_Delete.setObjectName("pushButton_Delete")
        self.tableView_employeeList = QtWidgets.QTableView(Dialog_ConfigModel)
        self.tableView_employeeList.setGeometry(QtCore.QRect(270, 20, 511, 521))
        self.tableView_employeeList.setObjectName("tableView_employeeList")
        self.pushButton_Update = QtWidgets.QPushButton(Dialog_ConfigModel)
        self.pushButton_Update.setGeometry(QtCore.QRect(40, 280, 75, 23))
        self.pushButton_Update.setObjectName("pushButton_Update")
        self.pushButton_Clear = QtWidgets.QPushButton(Dialog_ConfigModel)
        self.pushButton_Clear.setGeometry(QtCore.QRect(40, 240, 75, 23))
        self.pushButton_Clear.setObjectName("pushButton_Clear")

        self.retranslateUi(Dialog_ConfigModel)
        self.pushButton_Close.clicked.connect(Dialog_ConfigModel.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_ConfigModel)
        Dialog_ConfigModel.setTabOrder(self.lineEdit_EmployeeCode, self.lineEdit_EmployeeName)
        Dialog_ConfigModel.setTabOrder(self.lineEdit_EmployeeName, self.pushButton_Clear)
        Dialog_ConfigModel.setTabOrder(self.pushButton_Clear, self.pushButton_Insert)
        Dialog_ConfigModel.setTabOrder(self.pushButton_Insert, self.pushButton_Update)
        Dialog_ConfigModel.setTabOrder(self.pushButton_Update, self.pushButton_Delete)
        Dialog_ConfigModel.setTabOrder(self.pushButton_Delete, self.tableView_employeeList)
        Dialog_ConfigModel.setTabOrder(self.tableView_employeeList, self.pushButton_Close)

    def retranslateUi(self, Dialog_ConfigModel):
        _translate = QtCore.QCoreApplication.translate
        Dialog_ConfigModel.setWindowTitle(_translate("Dialog_ConfigModel", "Config Employee"))
        self.pushButton_Close.setText(_translate("Dialog_ConfigModel", "Close"))
        self.groupBox.setTitle(_translate("Dialog_ConfigModel", "Information"))
        self.label_2.setText(_translate("Dialog_ConfigModel", "Employee Name (*)"))
        self.label_3.setText(_translate("Dialog_ConfigModel", "(*) : Input is requirement"))
        self.label_5.setText(_translate("Dialog_ConfigModel", "Employee Code (*)"))
        self.label_4.setText(_translate("Dialog_ConfigModel", "Email (*)"))
        self.pushButton_Insert.setText(_translate("Dialog_ConfigModel", "Add New"))
        self.pushButton_Delete.setText(_translate("Dialog_ConfigModel", "Delete"))
        self.pushButton_Update.setText(_translate("Dialog_ConfigModel", "Update"))
        self.pushButton_Clear.setText(_translate("Dialog_ConfigModel", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_ConfigModel = QtWidgets.QDialog()
    ui = Ui_Dialog_ConfigModel()
    ui.setupUi(Dialog_ConfigModel)
    Dialog_ConfigModel.show()
    sys.exit(app.exec_())
