# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/ConfigItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_ConfigModel(object):
    def setupUi(self, Dialog_ConfigModel):
        Dialog_ConfigModel.setObjectName("Dialog_ConfigModel")
        Dialog_ConfigModel.resize(800, 600)
        self.pushButton_Close = QtWidgets.QPushButton(Dialog_ConfigModel)
        self.pushButton_Close.setGeometry(QtCore.QRect(710, 560, 75, 23))
        self.pushButton_Close.setObjectName("pushButton_Close")
        self.groupBox = QtWidgets.QGroupBox(Dialog_ConfigModel)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 231, 251))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 131, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_ItemName = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_ItemName.setGeometry(QtCore.QRect(10, 90, 211, 20))
        self.lineEdit_ItemName.setObjectName("lineEdit_ItemName")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 220, 131, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_ItemCode = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_ItemCode.setGeometry(QtCore.QRect(10, 40, 211, 20))
        self.lineEdit_ItemCode.setReadOnly(False)
        self.lineEdit_ItemCode.setObjectName("lineEdit_ItemCode")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_Money = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Money.setGeometry(QtCore.QRect(10, 140, 211, 20))
        self.lineEdit_Money.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_Money.setObjectName("lineEdit_Money")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 170, 81, 16))
        self.label_6.setObjectName("label_6")
        self.comboBox_Employee = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Employee.setGeometry(QtCore.QRect(10, 190, 211, 22))
        self.comboBox_Employee.setObjectName("comboBox_Employee")
        self.pushButton_Insert = QtWidgets.QPushButton(Dialog_ConfigModel)
        self.pushButton_Insert.setGeometry(QtCore.QRect(150, 290, 75, 23))
        self.pushButton_Insert.setObjectName("pushButton_Insert")
        self.pushButton_Delete = QtWidgets.QPushButton(Dialog_ConfigModel)
        self.pushButton_Delete.setGeometry(QtCore.QRect(150, 330, 75, 23))
        self.pushButton_Delete.setObjectName("pushButton_Delete")
        self.tableView_itemList = QtWidgets.QTableView(Dialog_ConfigModel)
        self.tableView_itemList.setGeometry(QtCore.QRect(270, 20, 511, 521))
        self.tableView_itemList.setObjectName("tableView_itemList")
        self.pushButton_Update = QtWidgets.QPushButton(Dialog_ConfigModel)
        self.pushButton_Update.setGeometry(QtCore.QRect(40, 330, 75, 23))
        self.pushButton_Update.setObjectName("pushButton_Update")
        self.pushButton_Clear = QtWidgets.QPushButton(Dialog_ConfigModel)
        self.pushButton_Clear.setGeometry(QtCore.QRect(40, 290, 75, 23))
        self.pushButton_Clear.setObjectName("pushButton_Clear")

        self.retranslateUi(Dialog_ConfigModel)
        self.pushButton_Close.clicked.connect(Dialog_ConfigModel.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_ConfigModel)
        Dialog_ConfigModel.setTabOrder(self.lineEdit_ItemCode, self.lineEdit_ItemName)
        Dialog_ConfigModel.setTabOrder(self.lineEdit_ItemName, self.lineEdit_Money)
        Dialog_ConfigModel.setTabOrder(self.lineEdit_Money, self.comboBox_Employee)
        Dialog_ConfigModel.setTabOrder(self.comboBox_Employee, self.pushButton_Clear)
        Dialog_ConfigModel.setTabOrder(self.pushButton_Clear, self.pushButton_Insert)
        Dialog_ConfigModel.setTabOrder(self.pushButton_Insert, self.pushButton_Update)
        Dialog_ConfigModel.setTabOrder(self.pushButton_Update, self.pushButton_Delete)
        Dialog_ConfigModel.setTabOrder(self.pushButton_Delete, self.tableView_itemList)
        Dialog_ConfigModel.setTabOrder(self.tableView_itemList, self.pushButton_Close)

    def retranslateUi(self, Dialog_ConfigModel):
        _translate = QtCore.QCoreApplication.translate
        Dialog_ConfigModel.setWindowTitle(_translate("Dialog_ConfigModel", "Config Item"))
        self.pushButton_Close.setText(_translate("Dialog_ConfigModel", "Close"))
        self.groupBox.setTitle(_translate("Dialog_ConfigModel", "Information"))
        self.label_2.setText(_translate("Dialog_ConfigModel", "Item Name (*)"))
        self.label_4.setText(_translate("Dialog_ConfigModel", "Money (*)"))
        self.label_3.setText(_translate("Dialog_ConfigModel", "(*) : Input is requirement"))
        self.label_5.setText(_translate("Dialog_ConfigModel", "Item Code (*)"))
        self.label_6.setText(_translate("Dialog_ConfigModel", "Employee (*)"))
        self.pushButton_Insert.setText(_translate("Dialog_ConfigModel", "Add New"))
        self.pushButton_Delete.setText(_translate("Dialog_ConfigModel", "Delete"))
        self.pushButton_Update.setText(_translate("Dialog_ConfigModel", "Update"))
        self.pushButton_Clear.setText(_translate("Dialog_ConfigModel", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_ConfigModel = QtWidgets.QDialog()
    ui = Ui_Dialog_ConfigModel()
    ui.setupUi(Dialog_ConfigModel)
    Dialog_ConfigModel.show()
    sys.exit(app.exec_())
